version: '3.9'
services:
  gradle:
    image: gradle:7.1-jdk16
    ports:
      - "8080:8080"
      - "5005:5005"
      - "35729:35729"
    volumes:
      - ".:/app"
    working_dir: "/app"
    entrypoint: "./docker-entrypoint.sh"
